### ISSUE TITLE
Sorting Rows 

### ISSUE THREAD

**Issue by EvyK** [JelteMX/mendix-dynamic-table#4] opened 2020-03-27 08:20 UTC
Is it possible to sort the rows? I tried sorting in the input microflow, but it still ends up in random order.

**Comment by JelteMX** [comment] 2020-03-27 13:55
Oh, that's weird. It should follow the order of objects coming in. I will investigate. I am also thinking of adding an extra sort field, so you can set this in the widget.

**Comment by JelteMX** [comment] 2020-04-03 11:53
So, I analyzed the issue, but cannot reproduce it. If I use a microflow to get the rows, the objects that are shown are in order. Is this possibly in the child rows?

Anyway, I will be working on adding sorting attributes to both rows & columns, so you have a little bit more control over it.

**Comment by JelteMX** [comment] 2020-04-03 13:36
I still don't think it should be a problem, but... I have just released [1.3.0](https://github.com/JelteMX/mendix-dynamic-table/releases/tag/1.3.0) in the App Store, that adds a sorting attribute (currently only String/Number) to your rows & columns. That should definitely fix your issues. Closing this one for now

**Closed by JelteMX** 2020-04-03 13:36 UTC
Labels: enhancement
